/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, Interface } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_token",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_minAllowance",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_innerInput",
                type: "bytes",
            },
        ],
        name: "approvalBased",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes",
                name: "input",
                type: "bytes",
            },
        ],
        name: "general",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
export class IPaymasterFlow__factory {
    static createInterface() {
        return new Interface(_abi);
    }
    static connect(address, runner) {
        return new Contract(address, _abi, runner);
    }
}
IPaymasterFlow__factory.abi = _abi;
//# sourceMappingURL=IPaymasterFlow__factory.js.map