/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IBridgehubInterface extends ethers.utils.Interface {
  functions: {
    "acceptAdmin()": FunctionFragment;
    "addStateTransitionManager(address)": FunctionFragment;
    "addToken(address)": FunctionFragment;
    "baseToken(uint256)": FunctionFragment;
    "createNewChain(uint256,address,address,uint256,address,bytes)": FunctionFragment;
    "getHyperchain(uint256)": FunctionFragment;
    "l2TransactionBaseCost(uint256,uint256,uint256,uint256)": FunctionFragment;
    "proveL1ToL2TransactionStatus(uint256,bytes32,uint256,uint256,uint16,bytes32[],uint8)": FunctionFragment;
    "proveL2LogInclusion(uint256,uint256,uint256,tuple,bytes32[])": FunctionFragment;
    "proveL2MessageInclusion(uint256,uint256,uint256,tuple,bytes32[])": FunctionFragment;
    "removeStateTransitionManager(address)": FunctionFragment;
    "requestL2TransactionDirect(tuple)": FunctionFragment;
    "requestL2TransactionTwoBridges(tuple)": FunctionFragment;
    "setPendingAdmin(address)": FunctionFragment;
    "setSharedBridge(address)": FunctionFragment;
    "sharedBridge()": FunctionFragment;
    "stateTransitionManager(uint256)": FunctionFragment;
    "stateTransitionManagerIsRegistered(address)": FunctionFragment;
    "tokenIsRegistered(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addStateTransitionManager",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "addToken", values: [string]): string;
  encodeFunctionData(
    functionFragment: "baseToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewChain",
    values: [BigNumberish, string, string, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHyperchain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "l2TransactionBaseCost",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proveL1ToL2TransactionStatus",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proveL2LogInclusion",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proveL2MessageInclusion",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      { txNumberInBatch: BigNumberish; sender: string; data: BytesLike },
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeStateTransitionManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestL2TransactionDirect",
    values: [
      {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestL2TransactionTwoBridges",
    values: [
      {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPendingAdmin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSharedBridge",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sharedBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateTransitionManager",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stateTransitionManagerIsRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIsRegistered",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addStateTransitionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNewChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHyperchain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2TransactionBaseCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveL1ToL2TransactionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveL2LogInclusion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveL2MessageInclusion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeStateTransitionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestL2TransactionDirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestL2TransactionTwoBridges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateTransitionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateTransitionManagerIsRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIsRegistered",
    data: BytesLike
  ): Result;

  events: {
    "NewAdmin(address,address)": EventFragment;
    "NewChain(uint256,address,address)": EventFragment;
    "NewPendingAdmin(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewChain"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPendingAdmin"): EventFragment;
}

export class IBridgehub extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IBridgehubInterface;

  functions: {
    acceptAdmin(overrides?: Overrides): Promise<ContractTransaction>;

    "acceptAdmin()"(overrides?: Overrides): Promise<ContractTransaction>;

    addStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addToken(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    baseToken(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "baseToken(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    createNewChain(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createNewChain(uint256,address,address,uint256,address,bytes)"(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getHyperchain(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getHyperchain(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    l2TransactionBaseCost(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "l2TransactionBaseCost(uint256,uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    proveL1ToL2TransactionStatus(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "proveL1ToL2TransactionStatus(uint256,bytes32,uint256,uint256,uint16,bytes32[],uint8)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    proveL2LogInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "proveL2LogInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    proveL2MessageInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "proveL2MessageInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    removeStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    requestL2TransactionDirect(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "requestL2TransactionDirect(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    requestL2TransactionTwoBridges(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "requestL2TransactionTwoBridges(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    setPendingAdmin(
      _newPendingAdmin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPendingAdmin(address)"(
      _newPendingAdmin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSharedBridge(
      _sharedBridge: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSharedBridge(address)"(
      _sharedBridge: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sharedBridge(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "sharedBridge()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    stateTransitionManager(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "stateTransitionManager(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    stateTransitionManagerIsRegistered(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "stateTransitionManagerIsRegistered(address)"(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    tokenIsRegistered(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "tokenIsRegistered(address)"(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  acceptAdmin(overrides?: Overrides): Promise<ContractTransaction>;

  "acceptAdmin()"(overrides?: Overrides): Promise<ContractTransaction>;

  addStateTransitionManager(
    _stateTransitionManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addStateTransitionManager(address)"(
    _stateTransitionManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addToken(_token: string, overrides?: Overrides): Promise<ContractTransaction>;

  "addToken(address)"(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  baseToken(_chainId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "baseToken(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  createNewChain(
    _chainId: BigNumberish,
    _stateTransitionManager: string,
    _baseToken: string,
    _salt: BigNumberish,
    _admin: string,
    _initData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createNewChain(uint256,address,address,uint256,address,bytes)"(
    _chainId: BigNumberish,
    _stateTransitionManager: string,
    _baseToken: string,
    _salt: BigNumberish,
    _admin: string,
    _initData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getHyperchain(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getHyperchain(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  l2TransactionBaseCost(
    _chainId: BigNumberish,
    _gasPrice: BigNumberish,
    _l2GasLimit: BigNumberish,
    _l2GasPerPubdataByteLimit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "l2TransactionBaseCost(uint256,uint256,uint256,uint256)"(
    _chainId: BigNumberish,
    _gasPrice: BigNumberish,
    _l2GasLimit: BigNumberish,
    _l2GasPerPubdataByteLimit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proveL1ToL2TransactionStatus(
    _chainId: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    _status: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "proveL1ToL2TransactionStatus(uint256,bytes32,uint256,uint256,uint16,bytes32[],uint8)"(
    _chainId: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    _status: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  proveL2LogInclusion(
    _chainId: BigNumberish,
    _batchNumber: BigNumberish,
    _index: BigNumberish,
    _log: {
      l2ShardId: BigNumberish;
      isService: boolean;
      txNumberInBatch: BigNumberish;
      sender: string;
      key: BytesLike;
      value: BytesLike;
    },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "proveL2LogInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
    _chainId: BigNumberish,
    _batchNumber: BigNumberish,
    _index: BigNumberish,
    _log: {
      l2ShardId: BigNumberish;
      isService: boolean;
      txNumberInBatch: BigNumberish;
      sender: string;
      key: BytesLike;
      value: BytesLike;
    },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  proveL2MessageInclusion(
    _chainId: BigNumberish,
    _batchNumber: BigNumberish,
    _index: BigNumberish,
    _message: {
      txNumberInBatch: BigNumberish;
      sender: string;
      data: BytesLike;
    },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "proveL2MessageInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
    _chainId: BigNumberish,
    _batchNumber: BigNumberish,
    _index: BigNumberish,
    _message: {
      txNumberInBatch: BigNumberish;
      sender: string;
      data: BytesLike;
    },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeStateTransitionManager(
    _stateTransitionManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeStateTransitionManager(address)"(
    _stateTransitionManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  requestL2TransactionDirect(
    _request: {
      chainId: BigNumberish;
      mintValue: BigNumberish;
      l2Contract: string;
      l2Value: BigNumberish;
      l2Calldata: BytesLike;
      l2GasLimit: BigNumberish;
      l2GasPerPubdataByteLimit: BigNumberish;
      factoryDeps: BytesLike[];
      refundRecipient: string;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "requestL2TransactionDirect(tuple)"(
    _request: {
      chainId: BigNumberish;
      mintValue: BigNumberish;
      l2Contract: string;
      l2Value: BigNumberish;
      l2Calldata: BytesLike;
      l2GasLimit: BigNumberish;
      l2GasPerPubdataByteLimit: BigNumberish;
      factoryDeps: BytesLike[];
      refundRecipient: string;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  requestL2TransactionTwoBridges(
    _request: {
      chainId: BigNumberish;
      mintValue: BigNumberish;
      l2Value: BigNumberish;
      l2GasLimit: BigNumberish;
      l2GasPerPubdataByteLimit: BigNumberish;
      refundRecipient: string;
      secondBridgeAddress: string;
      secondBridgeValue: BigNumberish;
      secondBridgeCalldata: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "requestL2TransactionTwoBridges(tuple)"(
    _request: {
      chainId: BigNumberish;
      mintValue: BigNumberish;
      l2Value: BigNumberish;
      l2GasLimit: BigNumberish;
      l2GasPerPubdataByteLimit: BigNumberish;
      refundRecipient: string;
      secondBridgeAddress: string;
      secondBridgeValue: BigNumberish;
      secondBridgeCalldata: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  setPendingAdmin(
    _newPendingAdmin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPendingAdmin(address)"(
    _newPendingAdmin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSharedBridge(
    _sharedBridge: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSharedBridge(address)"(
    _sharedBridge: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sharedBridge(overrides?: CallOverrides): Promise<string>;

  "sharedBridge()"(overrides?: CallOverrides): Promise<string>;

  stateTransitionManager(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "stateTransitionManager(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  stateTransitionManagerIsRegistered(
    _stateTransitionManager: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "stateTransitionManagerIsRegistered(address)"(
    _stateTransitionManager: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tokenIsRegistered(
    _baseToken: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "tokenIsRegistered(address)"(
    _baseToken: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    acceptAdmin(overrides?: CallOverrides): Promise<void>;

    "acceptAdmin()"(overrides?: CallOverrides): Promise<void>;

    addStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addToken(_token: string, overrides?: CallOverrides): Promise<void>;

    "addToken(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    baseToken(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "baseToken(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    createNewChain(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "createNewChain(uint256,address,address,uint256,address,bytes)"(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHyperchain(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getHyperchain(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    l2TransactionBaseCost(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2TransactionBaseCost(uint256,uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proveL1ToL2TransactionStatus(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "proveL1ToL2TransactionStatus(uint256,bytes32,uint256,uint256,uint16,bytes32[],uint8)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proveL2LogInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "proveL2LogInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    proveL2MessageInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "proveL2MessageInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    requestL2TransactionDirect(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "requestL2TransactionDirect(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    requestL2TransactionTwoBridges(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "requestL2TransactionTwoBridges(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    setPendingAdmin(
      _newPendingAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPendingAdmin(address)"(
      _newPendingAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSharedBridge(
      _sharedBridge: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSharedBridge(address)"(
      _sharedBridge: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sharedBridge(overrides?: CallOverrides): Promise<string>;

    "sharedBridge()"(overrides?: CallOverrides): Promise<string>;

    stateTransitionManager(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "stateTransitionManager(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    stateTransitionManagerIsRegistered(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "stateTransitionManagerIsRegistered(address)"(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokenIsRegistered(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "tokenIsRegistered(address)"(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    NewAdmin(oldAdmin: string | null, newAdmin: string | null): EventFilter;

    NewChain(
      chainId: BigNumberish | null,
      stateTransitionManager: null,
      chainGovernance: string | null
    ): EventFilter;

    NewPendingAdmin(
      oldPendingAdmin: string | null,
      newPendingAdmin: string | null
    ): EventFilter;
  };

  estimateGas: {
    acceptAdmin(overrides?: Overrides): Promise<BigNumber>;

    "acceptAdmin()"(overrides?: Overrides): Promise<BigNumber>;

    addStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addToken(_token: string, overrides?: Overrides): Promise<BigNumber>;

    "addToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    baseToken(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "baseToken(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createNewChain(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createNewChain(uint256,address,address,uint256,address,bytes)"(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getHyperchain(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getHyperchain(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2TransactionBaseCost(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2TransactionBaseCost(uint256,uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proveL1ToL2TransactionStatus(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proveL1ToL2TransactionStatus(uint256,bytes32,uint256,uint256,uint16,bytes32[],uint8)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proveL2LogInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proveL2LogInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proveL2MessageInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proveL2MessageInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    requestL2TransactionDirect(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "requestL2TransactionDirect(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    requestL2TransactionTwoBridges(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "requestL2TransactionTwoBridges(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    setPendingAdmin(
      _newPendingAdmin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPendingAdmin(address)"(
      _newPendingAdmin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSharedBridge(
      _sharedBridge: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setSharedBridge(address)"(
      _sharedBridge: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sharedBridge(overrides?: CallOverrides): Promise<BigNumber>;

    "sharedBridge()"(overrides?: CallOverrides): Promise<BigNumber>;

    stateTransitionManager(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "stateTransitionManager(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stateTransitionManagerIsRegistered(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "stateTransitionManagerIsRegistered(address)"(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenIsRegistered(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenIsRegistered(address)"(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptAdmin(overrides?: Overrides): Promise<PopulatedTransaction>;

    "acceptAdmin()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    addStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addToken(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    baseToken(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "baseToken(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createNewChain(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createNewChain(uint256,address,address,uint256,address,bytes)"(
      _chainId: BigNumberish,
      _stateTransitionManager: string,
      _baseToken: string,
      _salt: BigNumberish,
      _admin: string,
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getHyperchain(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getHyperchain(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2TransactionBaseCost(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l2TransactionBaseCost(uint256,uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _gasPrice: BigNumberish,
      _l2GasLimit: BigNumberish,
      _l2GasPerPubdataByteLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proveL1ToL2TransactionStatus(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proveL1ToL2TransactionStatus(uint256,bytes32,uint256,uint256,uint16,bytes32[],uint8)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proveL2LogInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proveL2LogInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _log: {
        l2ShardId: BigNumberish;
        isService: boolean;
        txNumberInBatch: BigNumberish;
        sender: string;
        key: BytesLike;
        value: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proveL2MessageInclusion(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proveL2MessageInclusion(uint256,uint256,uint256,tuple,bytes32[])"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _index: BigNumberish,
      _message: {
        txNumberInBatch: BigNumberish;
        sender: string;
        data: BytesLike;
      },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeStateTransitionManager(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeStateTransitionManager(address)"(
      _stateTransitionManager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    requestL2TransactionDirect(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "requestL2TransactionDirect(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Contract: string;
        l2Value: BigNumberish;
        l2Calldata: BytesLike;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        factoryDeps: BytesLike[];
        refundRecipient: string;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    requestL2TransactionTwoBridges(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "requestL2TransactionTwoBridges(tuple)"(
      _request: {
        chainId: BigNumberish;
        mintValue: BigNumberish;
        l2Value: BigNumberish;
        l2GasLimit: BigNumberish;
        l2GasPerPubdataByteLimit: BigNumberish;
        refundRecipient: string;
        secondBridgeAddress: string;
        secondBridgeValue: BigNumberish;
        secondBridgeCalldata: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    setPendingAdmin(
      _newPendingAdmin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPendingAdmin(address)"(
      _newPendingAdmin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSharedBridge(
      _sharedBridge: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSharedBridge(address)"(
      _sharedBridge: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sharedBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sharedBridge()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stateTransitionManager(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "stateTransitionManager(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stateTransitionManagerIsRegistered(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "stateTransitionManagerIsRegistered(address)"(
      _stateTransitionManager: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenIsRegistered(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenIsRegistered(address)"(
      _baseToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
