/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Il1SharedBridgeInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_HUB()": FunctionFragment;
    "L1_WETH_TOKEN()": FunctionFragment;
    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)": FunctionFragment;
    "bridgehubDeposit(uint256,address,uint256,bytes)": FunctionFragment;
    "bridgehubDepositBaseToken(uint256,address,address,uint256)": FunctionFragment;
    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])": FunctionFragment;
    "claimFailedDepositLegacyErc20Bridge(address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])": FunctionFragment;
    "depositHappened(uint256,bytes32)": FunctionFragment;
    "depositLegacyErc20Bridge(address,address,address,uint256,uint256,uint256,address)": FunctionFragment;
    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])": FunctionFragment;
    "finalizeWithdrawalLegacyErc20Bridge(uint256,uint256,uint16,bytes,bytes32[])": FunctionFragment;
    "isWithdrawalFinalized(uint256,uint256,uint256)": FunctionFragment;
    "l2BridgeAddress(uint256)": FunctionFragment;
    "legacyBridge()": FunctionFragment;
    "receiveEth(uint256)": FunctionFragment;
    "setEraLegacyBridgeLastDepositTime(uint256,uint256)": FunctionFragment;
    "setEraPostDiamondUpgradeFirstBatch(uint256)": FunctionFragment;
    "setEraPostLegacyBridgeUpgradeFirstBatch(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L1_WETH_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubConfirmL2Transaction",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubDeposit",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubDepositBaseToken",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFailedDeposit",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFailedDepositLegacyErc20Bridge",
    values: [
      string,
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositHappened",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositLegacyErc20Bridge",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawal",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawalLegacyErc20Bridge",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isWithdrawalFinalized",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "l2BridgeAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "legacyBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveEth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEraLegacyBridgeLastDepositTime",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEraPostDiamondUpgradeFirstBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEraPostLegacyBridgeUpgradeFirstBatch",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "L1_WETH_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubConfirmL2Transaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubDepositBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFailedDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFailedDepositLegacyErc20Bridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositHappened",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositLegacyErc20Bridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawalLegacyErc20Bridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWithdrawalFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2BridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "legacyBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receiveEth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEraLegacyBridgeLastDepositTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEraPostDiamondUpgradeFirstBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEraPostLegacyBridgeUpgradeFirstBatch",
    data: BytesLike
  ): Result;

  events: {
    "BridgehubDepositBaseTokenInitiated(uint256,address,address,uint256)": EventFragment;
    "BridgehubDepositFinalized(uint256,bytes32,bytes32)": EventFragment;
    "BridgehubDepositInitiated(uint256,bytes32,address,address,address,uint256)": EventFragment;
    "ClaimedFailedDepositSharedBridge(uint256,address,address,uint256)": EventFragment;
    "LegacyDepositInitiated(uint256,bytes32,address,address,address,uint256)": EventFragment;
    "WithdrawalFinalizedSharedBridge(uint256,address,address,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "BridgehubDepositBaseTokenInitiated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BridgehubDepositFinalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BridgehubDepositInitiated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ClaimedFailedDepositSharedBridge"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LegacyDepositInitiated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WithdrawalFinalizedSharedBridge"
  ): EventFragment;
}

export class Il1SharedBridge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Il1SharedBridgeInterface;

  functions: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    L1_WETH_TOKEN(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "L1_WETH_TOKEN()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimFailedDepositLegacyErc20Bridge(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimFailedDepositLegacyErc20Bridge(address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    depositLegacyErc20Bridge(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "depositLegacyErc20Bridge(address,address,address,uint256,uint256,uint256,address)"(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    finalizeWithdrawalLegacyErc20Bridge(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "finalizeWithdrawalLegacyErc20Bridge(uint256,uint256,uint16,bytes,bytes32[])"(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isWithdrawalFinalized(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isWithdrawalFinalized(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    legacyBridge(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "legacyBridge()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    receiveEth(
      _chainId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "receiveEth(uint256)"(
      _chainId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    setEraLegacyBridgeLastDepositTime(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setEraLegacyBridgeLastDepositTime(uint256,uint256)"(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setEraPostDiamondUpgradeFirstBatch(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setEraPostDiamondUpgradeFirstBatch(uint256)"(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setEraPostLegacyBridgeUpgradeFirstBatch(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setEraPostLegacyBridgeUpgradeFirstBatch(uint256)"(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

  L1_WETH_TOKEN(overrides?: CallOverrides): Promise<string>;

  "L1_WETH_TOKEN()"(overrides?: CallOverrides): Promise<string>;

  bridgehubConfirmL2Transaction(
    _chainId: BigNumberish,
    _txDataHash: BytesLike,
    _txHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
    _chainId: BigNumberish,
    _txDataHash: BytesLike,
    _txHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bridgehubDeposit(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _l2Value: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDeposit(uint256,address,uint256,bytes)"(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _l2Value: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  bridgehubDepositBaseToken(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  claimFailedDeposit(
    _chainId: BigNumberish,
    _depositSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
    _chainId: BigNumberish,
    _depositSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimFailedDepositLegacyErc20Bridge(
    _depositSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimFailedDepositLegacyErc20Bridge(address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
    _depositSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  depositHappened(
    _chainId: BigNumberish,
    _l2TxHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "depositHappened(uint256,bytes32)"(
    _chainId: BigNumberish,
    _l2TxHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  depositLegacyErc20Bridge(
    _msgSender: string,
    _l2Receiver: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxGasLimit: BigNumberish,
    _l2TxGasPerPubdataByte: BigNumberish,
    _refundRecipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "depositLegacyErc20Bridge(address,address,address,uint256,uint256,uint256,address)"(
    _msgSender: string,
    _l2Receiver: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxGasLimit: BigNumberish,
    _l2TxGasPerPubdataByte: BigNumberish,
    _refundRecipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  finalizeWithdrawal(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _message: BytesLike,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _message: BytesLike,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  finalizeWithdrawalLegacyErc20Bridge(
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _message: BytesLike,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "finalizeWithdrawalLegacyErc20Bridge(uint256,uint256,uint16,bytes,bytes32[])"(
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _message: BytesLike,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isWithdrawalFinalized(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isWithdrawalFinalized(uint256,uint256,uint256)"(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  l2BridgeAddress(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "l2BridgeAddress(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  legacyBridge(overrides?: CallOverrides): Promise<string>;

  "legacyBridge()"(overrides?: CallOverrides): Promise<string>;

  receiveEth(
    _chainId: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "receiveEth(uint256)"(
    _chainId: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  setEraLegacyBridgeLastDepositTime(
    _eraLegacyBridgeLastDepositBatch: BigNumberish,
    _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setEraLegacyBridgeLastDepositTime(uint256,uint256)"(
    _eraLegacyBridgeLastDepositBatch: BigNumberish,
    _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setEraPostDiamondUpgradeFirstBatch(
    _eraPostDiamondUpgradeFirstBatch: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setEraPostDiamondUpgradeFirstBatch(uint256)"(
    _eraPostDiamondUpgradeFirstBatch: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setEraPostLegacyBridgeUpgradeFirstBatch(
    _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setEraPostLegacyBridgeUpgradeFirstBatch(uint256)"(
    _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

    L1_WETH_TOKEN(overrides?: CallOverrides): Promise<string>;

    "L1_WETH_TOKEN()"(overrides?: CallOverrides): Promise<string>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimFailedDepositLegacyErc20Bridge(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "claimFailedDepositLegacyErc20Bridge(address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    depositLegacyErc20Bridge(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "depositLegacyErc20Bridge(address,address,address,uint256,uint256,uint256,address)"(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: CallOverrides
    ): Promise<string>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeWithdrawalLegacyErc20Bridge(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      l1Receiver: string;
      l1Token: string;
      amount: BigNumber;
      0: string;
      1: string;
      2: BigNumber;
    }>;

    "finalizeWithdrawalLegacyErc20Bridge(uint256,uint256,uint16,bytes,bytes32[])"(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      l1Receiver: string;
      l1Token: string;
      amount: BigNumber;
      0: string;
      1: string;
      2: BigNumber;
    }>;

    isWithdrawalFinalized(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isWithdrawalFinalized(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    legacyBridge(overrides?: CallOverrides): Promise<string>;

    "legacyBridge()"(overrides?: CallOverrides): Promise<string>;

    receiveEth(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "receiveEth(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setEraLegacyBridgeLastDepositTime(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setEraLegacyBridgeLastDepositTime(uint256,uint256)"(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setEraPostDiamondUpgradeFirstBatch(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setEraPostDiamondUpgradeFirstBatch(uint256)"(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setEraPostLegacyBridgeUpgradeFirstBatch(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setEraPostLegacyBridgeUpgradeFirstBatch(uint256)"(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BridgehubDepositBaseTokenInitiated(
      chainId: BigNumberish | null,
      from: string | null,
      l1Token: null,
      amount: null
    ): EventFilter;

    BridgehubDepositFinalized(
      chainId: BigNumberish | null,
      txDataHash: BytesLike | null,
      l2DepositTxHash: BytesLike | null
    ): EventFilter;

    BridgehubDepositInitiated(
      chainId: BigNumberish | null,
      txDataHash: BytesLike | null,
      from: string | null,
      to: null,
      l1Token: null,
      amount: null
    ): EventFilter;

    ClaimedFailedDepositSharedBridge(
      chainId: BigNumberish | null,
      to: string | null,
      l1Token: string | null,
      amount: null
    ): EventFilter;

    LegacyDepositInitiated(
      chainId: BigNumberish | null,
      l2DepositTxHash: BytesLike | null,
      from: string | null,
      to: null,
      l1Token: null,
      amount: null
    ): EventFilter;

    WithdrawalFinalizedSharedBridge(
      chainId: BigNumberish | null,
      to: string | null,
      l1Token: string | null,
      amount: null
    ): EventFilter;
  };

  estimateGas: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    L1_WETH_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    "L1_WETH_TOKEN()"(overrides?: CallOverrides): Promise<BigNumber>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimFailedDepositLegacyErc20Bridge(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimFailedDepositLegacyErc20Bridge(address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositLegacyErc20Bridge(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "depositLegacyErc20Bridge(address,address,address,uint256,uint256,uint256,address)"(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    finalizeWithdrawalLegacyErc20Bridge(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "finalizeWithdrawalLegacyErc20Bridge(uint256,uint256,uint16,bytes,bytes32[])"(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    isWithdrawalFinalized(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isWithdrawalFinalized(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    legacyBridge(overrides?: CallOverrides): Promise<BigNumber>;

    "legacyBridge()"(overrides?: CallOverrides): Promise<BigNumber>;

    receiveEth(
      _chainId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "receiveEth(uint256)"(
      _chainId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    setEraLegacyBridgeLastDepositTime(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setEraLegacyBridgeLastDepositTime(uint256,uint256)"(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setEraPostDiamondUpgradeFirstBatch(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setEraPostDiamondUpgradeFirstBatch(uint256)"(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setEraPostLegacyBridgeUpgradeFirstBatch(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setEraPostLegacyBridgeUpgradeFirstBatch(uint256)"(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L1_WETH_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "L1_WETH_TOKEN()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimFailedDepositLegacyErc20Bridge(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimFailedDepositLegacyErc20Bridge(address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositLegacyErc20Bridge(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "depositLegacyErc20Bridge(address,address,address,uint256,uint256,uint256,address)"(
      _msgSender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    finalizeWithdrawalLegacyErc20Bridge(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "finalizeWithdrawalLegacyErc20Bridge(uint256,uint256,uint16,bytes,bytes32[])"(
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isWithdrawalFinalized(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isWithdrawalFinalized(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    legacyBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "legacyBridge()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveEth(
      _chainId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "receiveEth(uint256)"(
      _chainId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    setEraLegacyBridgeLastDepositTime(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setEraLegacyBridgeLastDepositTime(uint256,uint256)"(
      _eraLegacyBridgeLastDepositBatch: BigNumberish,
      _eraLegacyBridgeLastDepositTxNumber: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setEraPostDiamondUpgradeFirstBatch(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setEraPostDiamondUpgradeFirstBatch(uint256)"(
      _eraPostDiamondUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setEraPostLegacyBridgeUpgradeFirstBatch(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setEraPostLegacyBridgeUpgradeFirstBatch(uint256)"(
      _eraPostLegacyBridgeUpgradeFirstBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
