/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Il2AssetRouterInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_HUB()": FunctionFragment;
    "L1_ASSET_ROUTER()": FunctionFragment;
    "assetHandlerAddress(bytes32)": FunctionFragment;
    "finalizeDeposit(uint256,bytes32,bytes)": FunctionFragment;
    "finalizeDepositLegacyBridge(address,address,address,uint256,bytes)": FunctionFragment;
    "setAssetHandlerAddress(uint256,bytes32,address)": FunctionFragment;
    "setAssetHandlerAddressThisChain(bytes32,address)": FunctionFragment;
    "setLegacyTokenAssetHandler(bytes32)": FunctionFragment;
    "withdraw(bytes32,bytes)": FunctionFragment;
    "withdrawLegacyBridge(address,address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L1_ASSET_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetHandlerAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDeposit",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDepositLegacyBridge",
    values: [string, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetHandlerAddress",
    values: [BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetHandlerAddressThisChain",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setLegacyTokenAssetHandler",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLegacyBridge",
    values: [string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "L1_ASSET_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetHandlerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDepositLegacyBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetHandlerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetHandlerAddressThisChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLegacyTokenAssetHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLegacyBridge",
    data: BytesLike
  ): Result;

  events: {
    "AssetDeploymentTrackerRegistered(bytes32,bytes32,address)": EventFragment;
    "AssetHandlerRegistered(bytes32,address)": EventFragment;
    "BridgehubDepositBaseTokenInitiated(uint256,address,bytes32,uint256)": EventFragment;
    "BridgehubDepositInitiated(uint256,bytes32,address,bytes32,bytes)": EventFragment;
    "BridgehubWithdrawalInitiated(uint256,address,bytes32,bytes32)": EventFragment;
    "DepositFinalizedAssetRouter(uint256,bytes32,bytes)": EventFragment;
    "WithdrawalInitiatedAssetRouter(uint256,address,bytes32,bytes)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AssetDeploymentTrackerRegistered"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetHandlerRegistered"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BridgehubDepositBaseTokenInitiated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BridgehubDepositInitiated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BridgehubWithdrawalInitiated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DepositFinalizedAssetRouter"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WithdrawalInitiatedAssetRouter"
  ): EventFragment;
}

export class Il2AssetRouter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Il2AssetRouterInterface;

  functions: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    assetHandlerAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "assetHandlerAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    finalizeDeposit(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "finalizeDeposit(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    finalizeDepositLegacyBridge(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "finalizeDepositLegacyBridge(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setAssetHandlerAddress(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAssetHandlerAddress(uint256,bytes32,address)"(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setAssetHandlerAddressThisChain(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAssetHandlerAddressThisChain(bytes32,address)"(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setLegacyTokenAssetHandler(
      _assetId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLegacyTokenAssetHandler(bytes32)"(
      _assetId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(bytes32,bytes)"(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawLegacyBridge(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawLegacyBridge(address,address,uint256,address)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

  L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<string>;

  "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<string>;

  assetHandlerAddress(
    _assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "assetHandlerAddress(bytes32)"(
    _assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  finalizeDeposit(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _transferData: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "finalizeDeposit(uint256,bytes32,bytes)"(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _transferData: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  finalizeDepositLegacyBridge(
    _l1Sender: string,
    _l2Receiver: string,
    _l1Token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "finalizeDepositLegacyBridge(address,address,address,uint256,bytes)"(
    _l1Sender: string,
    _l2Receiver: string,
    _l1Token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setAssetHandlerAddress(
    _originChainId: BigNumberish,
    _assetId: BytesLike,
    _assetHandlerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAssetHandlerAddress(uint256,bytes32,address)"(
    _originChainId: BigNumberish,
    _assetId: BytesLike,
    _assetHandlerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setAssetHandlerAddressThisChain(
    _assetRegistrationData: BytesLike,
    _assetHandlerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAssetHandlerAddressThisChain(bytes32,address)"(
    _assetRegistrationData: BytesLike,
    _assetHandlerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setLegacyTokenAssetHandler(
    _assetId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLegacyTokenAssetHandler(bytes32)"(
    _assetId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    _assetId: BytesLike,
    _transferData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(bytes32,bytes)"(
    _assetId: BytesLike,
    _transferData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawLegacyBridge(
    _l1Receiver: string,
    _l2Token: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawLegacyBridge(address,address,uint256,address)"(
    _l1Receiver: string,
    _l2Token: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<string>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<string>;

    assetHandlerAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "assetHandlerAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    finalizeDeposit(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "finalizeDeposit(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeDepositLegacyBridge(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "finalizeDepositLegacyBridge(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setAssetHandlerAddress(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAssetHandlerAddress(uint256,bytes32,address)"(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAssetHandlerAddressThisChain(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAssetHandlerAddressThisChain(bytes32,address)"(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setLegacyTokenAssetHandler(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLegacyTokenAssetHandler(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "withdraw(bytes32,bytes)"(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    withdrawLegacyBridge(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawLegacyBridge(address,address,uint256,address)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AssetDeploymentTrackerRegistered(
      assetId: BytesLike | null,
      additionalData: BytesLike | null,
      assetDeploymentTracker: null
    ): EventFilter;

    AssetHandlerRegistered(
      assetId: BytesLike | null,
      _assetHandlerAddress: string | null
    ): EventFilter;

    BridgehubDepositBaseTokenInitiated(
      chainId: BigNumberish | null,
      from: string | null,
      assetId: null,
      amount: null
    ): EventFilter;

    BridgehubDepositInitiated(
      chainId: BigNumberish | null,
      txDataHash: BytesLike | null,
      from: string | null,
      assetId: null,
      bridgeMintCalldata: null
    ): EventFilter;

    BridgehubWithdrawalInitiated(
      chainId: null,
      sender: string | null,
      assetId: BytesLike | null,
      assetDataHash: null
    ): EventFilter;

    DepositFinalizedAssetRouter(
      chainId: BigNumberish | null,
      assetId: BytesLike | null,
      assetData: null
    ): EventFilter;

    WithdrawalInitiatedAssetRouter(
      chainId: null,
      l2Sender: string | null,
      assetId: BytesLike | null,
      assetData: null
    ): EventFilter;
  };

  estimateGas: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<BigNumber>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetHandlerAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assetHandlerAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    finalizeDeposit(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "finalizeDeposit(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    finalizeDepositLegacyBridge(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "finalizeDepositLegacyBridge(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setAssetHandlerAddress(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAssetHandlerAddress(uint256,bytes32,address)"(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setAssetHandlerAddressThisChain(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAssetHandlerAddressThisChain(bytes32,address)"(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setLegacyTokenAssetHandler(
      _assetId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLegacyTokenAssetHandler(bytes32)"(
      _assetId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdraw(bytes32,bytes)"(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawLegacyBridge(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawLegacyBridge(address,address,uint256,address)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "L1_ASSET_ROUTER()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assetHandlerAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetHandlerAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    finalizeDeposit(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "finalizeDeposit(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    finalizeDepositLegacyBridge(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "finalizeDepositLegacyBridge(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setAssetHandlerAddress(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAssetHandlerAddress(uint256,bytes32,address)"(
      _originChainId: BigNumberish,
      _assetId: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setAssetHandlerAddressThisChain(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAssetHandlerAddressThisChain(bytes32,address)"(
      _assetRegistrationData: BytesLike,
      _assetHandlerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setLegacyTokenAssetHandler(
      _assetId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLegacyTokenAssetHandler(bytes32)"(
      _assetId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(bytes32,bytes)"(
      _assetId: BytesLike,
      _transferData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawLegacyBridge(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawLegacyBridge(address,address,uint256,address)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
