/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IContractDeployerInterface extends ethers.utils.Interface {
  functions: {
    "create(bytes32,bytes32,bytes)": FunctionFragment;
    "create2(bytes32,bytes32,bytes)": FunctionFragment;
    "create2Account(bytes32,bytes32,bytes,uint8)": FunctionFragment;
    "createAccount(bytes32,bytes32,bytes,uint8)": FunctionFragment;
    "getAccountInfo(address)": FunctionFragment;
    "getNewAddressCreate(address,uint256)": FunctionFragment;
    "getNewAddressCreate2(address,bytes32,bytes32,bytes)": FunctionFragment;
    "updateAccountVersion(uint8)": FunctionFragment;
    "updateNonceOrdering(uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "create2",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "create2Account",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewAddressCreate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewAddressCreate2",
    values: [string, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAccountVersion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateNonceOrdering",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "create2Account",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewAddressCreate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewAddressCreate2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAccountVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateNonceOrdering",
    data: BytesLike
  ): Result;

  events: {
    "AccountNonceOrderingUpdated(address,uint8)": EventFragment;
    "AccountVersionUpdated(address,uint8)": EventFragment;
    "ContractDeployed(address,bytes32,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AccountNonceOrderingUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountVersionUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractDeployed"): EventFragment;
}

export class IContractDeployer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: IContractDeployerInterface;

  functions: {
    create(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "create(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    create2Account(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "create2Account(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    createAccount(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "createAccount(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    getAccountInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number] & { supportedAAVersion: number; nonceOrdering: number }
      ] & {
        info: [number, number] & {
          supportedAAVersion: number;
          nonceOrdering: number;
        };
      }
    >;

    "getAccountInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number] & { supportedAAVersion: number; nonceOrdering: number }
      ] & {
        info: [number, number] & {
          supportedAAVersion: number;
          nonceOrdering: number;
        };
      }
    >;

    getNewAddressCreate(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { newAddress: string }>;

    "getNewAddressCreate(address,uint256)"(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { newAddress: string }>;

    getNewAddressCreate2(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { newAddress: string }>;

    "getNewAddressCreate2(address,bytes32,bytes32,bytes)"(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { newAddress: string }>;

    updateAccountVersion(
      _version: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateAccountVersion(uint8)"(
      _version: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateNonceOrdering(
      _nonceOrdering: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateNonceOrdering(uint8)"(
      _nonceOrdering: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  create(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "create(bytes32,bytes32,bytes)"(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  create2(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "create2(bytes32,bytes32,bytes)"(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  create2Account(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    _aaVersion: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "create2Account(bytes32,bytes32,bytes,uint8)"(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    _aaVersion: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  createAccount(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    _aaVersion: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "createAccount(bytes32,bytes32,bytes,uint8)"(
    _salt: BytesLike,
    _bytecodeHash: BytesLike,
    _input: BytesLike,
    _aaVersion: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  getAccountInfo(
    _address: string,
    overrides?: CallOverrides
  ): Promise<
    [number, number] & { supportedAAVersion: number; nonceOrdering: number }
  >;

  "getAccountInfo(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<
    [number, number] & { supportedAAVersion: number; nonceOrdering: number }
  >;

  getNewAddressCreate(
    _sender: string,
    _senderNonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getNewAddressCreate(address,uint256)"(
    _sender: string,
    _senderNonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getNewAddressCreate2(
    _sender: string,
    _bytecodeHash: BytesLike,
    _salt: BytesLike,
    _input: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getNewAddressCreate2(address,bytes32,bytes32,bytes)"(
    _sender: string,
    _bytecodeHash: BytesLike,
    _salt: BytesLike,
    _input: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  updateAccountVersion(
    _version: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateAccountVersion(uint8)"(
    _version: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateNonceOrdering(
    _nonceOrdering: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateNonceOrdering(uint8)"(
    _nonceOrdering: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    create(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "create(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    create2Account(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "create2Account(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    createAccount(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "createAccount(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getAccountInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { supportedAAVersion: number; nonceOrdering: number }
    >;

    "getAccountInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { supportedAAVersion: number; nonceOrdering: number }
    >;

    getNewAddressCreate(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getNewAddressCreate(address,uint256)"(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getNewAddressCreate2(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getNewAddressCreate2(address,bytes32,bytes32,bytes)"(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    updateAccountVersion(
      _version: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateAccountVersion(uint8)"(
      _version: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateNonceOrdering(
      _nonceOrdering: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateNonceOrdering(uint8)"(
      _nonceOrdering: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AccountNonceOrderingUpdated(
      accountAddress: string | null,
      nonceOrdering: null
    ): TypedEventFilter<
      [string, number],
      { accountAddress: string; nonceOrdering: number }
    >;

    AccountVersionUpdated(
      accountAddress: string | null,
      aaVersion: null
    ): TypedEventFilter<
      [string, number],
      { accountAddress: string; aaVersion: number }
    >;

    ContractDeployed(
      deployerAddress: string | null,
      bytecodeHash: BytesLike | null,
      contractAddress: string | null
    ): TypedEventFilter<
      [string, string, string],
      { deployerAddress: string; bytecodeHash: string; contractAddress: string }
    >;
  };

  estimateGas: {
    create(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "create(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    create2Account(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "create2Account(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    createAccount(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "createAccount(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    getAccountInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAccountInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewAddressCreate(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNewAddressCreate(address,uint256)"(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewAddressCreate2(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNewAddressCreate2(address,bytes32,bytes32,bytes)"(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAccountVersion(
      _version: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateAccountVersion(uint8)"(
      _version: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateNonceOrdering(
      _nonceOrdering: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateNonceOrdering(uint8)"(
      _nonceOrdering: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "create(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    create2(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "create2(bytes32,bytes32,bytes)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    create2Account(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "create2Account(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    createAccount(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "createAccount(bytes32,bytes32,bytes,uint8)"(
      _salt: BytesLike,
      _bytecodeHash: BytesLike,
      _input: BytesLike,
      _aaVersion: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    getAccountInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAccountInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNewAddressCreate(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNewAddressCreate(address,uint256)"(
      _sender: string,
      _senderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNewAddressCreate2(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNewAddressCreate2(address,bytes32,bytes32,bytes)"(
      _sender: string,
      _bytecodeHash: BytesLike,
      _salt: BytesLike,
      _input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAccountVersion(
      _version: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateAccountVersion(uint8)"(
      _version: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateNonceOrdering(
      _nonceOrdering: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateNonceOrdering(uint8)"(
      _nonceOrdering: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
