/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Il1BridgeInterface extends ethers.utils.Interface {
  functions: {
    "bridgehub()": FunctionFragment;
    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)": FunctionFragment;
    "bridgehubDeposit(uint256,address,bytes)": FunctionFragment;
    "bridgehubDepositBaseToken(uint256,address,address,uint256)": FunctionFragment;
    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])": FunctionFragment;
    "deposit(uint256,address,address,uint256,uint256,uint256,uint256,address)": FunctionFragment;
    "depositHappened(uint256,bytes32)": FunctionFragment;
    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])": FunctionFragment;
    "isWithdrawalFinalizedShared(uint256,uint256,uint256)": FunctionFragment;
    "l2BridgeAddress(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "bridgehub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bridgehubConfirmL2Transaction",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubDeposit",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubDepositBaseToken",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFailedDeposit",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositHappened",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawal",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isWithdrawalFinalizedShared",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "l2BridgeAddress",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bridgehub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubConfirmL2Transaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubDepositBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFailedDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositHappened",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWithdrawalFinalizedShared",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2BridgeAddress",
    data: BytesLike
  ): Result;

  events: {
    "BridgehubDepositFinalized(uint256,bytes32,bytes32)": EventFragment;
    "BridgehubDepositInitiatedSharedBridge(uint256,bytes32,address,address,address,uint256)": EventFragment;
    "ClaimedFailedDepositSharedBridge(uint256,address,address,uint256)": EventFragment;
    "DepositInitiatedSharedBridge(uint256,bytes32,address,address,address,uint256)": EventFragment;
    "WithdrawalFinalizedSharedBridge(uint256,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BridgehubDepositFinalized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BridgehubDepositInitiatedSharedBridge"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ClaimedFailedDepositSharedBridge"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DepositInitiatedSharedBridge"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WithdrawalFinalizedSharedBridge"
  ): EventFragment;
}

export class Il1Bridge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Il1BridgeInterface;

  functions: {
    bridgehub(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "bridgehub()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDeposit(uint256,address,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    deposit(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "deposit(uint256,address,address,uint256,uint256,uint256,uint256,address)"(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isWithdrawalFinalizedShared(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isWithdrawalFinalizedShared(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  bridgehub(overrides?: CallOverrides): Promise<string>;

  "bridgehub()"(overrides?: CallOverrides): Promise<string>;

  bridgehubConfirmL2Transaction(
    _chainId: BigNumberish,
    _txDataHash: BytesLike,
    _txHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
    _chainId: BigNumberish,
    _txDataHash: BytesLike,
    _txHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bridgehubDeposit(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDeposit(uint256,address,bytes)"(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  bridgehubDepositBaseToken(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
    _chainId: BigNumberish,
    _prevMsgSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  claimFailedDeposit(
    _chainId: BigNumberish,
    _depositSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
    _chainId: BigNumberish,
    _depositSender: string,
    _l1Token: string,
    _amount: BigNumberish,
    _l2TxHash: BytesLike,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  deposit(
    _chainId: BigNumberish,
    _l2Receiver: string,
    _l1Token: string,
    _mintValue: BigNumberish,
    _amount: BigNumberish,
    _l2TxGasLimit: BigNumberish,
    _l2TxGasPerPubdataByte: BigNumberish,
    _refundRecipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "deposit(uint256,address,address,uint256,uint256,uint256,uint256,address)"(
    _chainId: BigNumberish,
    _l2Receiver: string,
    _l1Token: string,
    _mintValue: BigNumberish,
    _amount: BigNumberish,
    _l2TxGasLimit: BigNumberish,
    _l2TxGasPerPubdataByte: BigNumberish,
    _refundRecipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  depositHappened(
    _chainId: BigNumberish,
    _l2TxHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "depositHappened(uint256,bytes32)"(
    _chainId: BigNumberish,
    _l2TxHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  finalizeWithdrawal(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _message: BytesLike,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    _l2TxNumberInBatch: BigNumberish,
    _message: BytesLike,
    _merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isWithdrawalFinalizedShared(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isWithdrawalFinalizedShared(uint256,uint256,uint256)"(
    _chainId: BigNumberish,
    _l2BatchNumber: BigNumberish,
    _l2MessageIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  l2BridgeAddress(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "l2BridgeAddress(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    bridgehub(overrides?: CallOverrides): Promise<string>;

    "bridgehub()"(overrides?: CallOverrides): Promise<string>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    "bridgehubDeposit(uint256,address,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "deposit(uint256,address,address,uint256,uint256,uint256,uint256,address)"(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: CallOverrides
    ): Promise<string>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    isWithdrawalFinalizedShared(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isWithdrawalFinalizedShared(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    BridgehubDepositFinalized(
      chainId: BigNumberish | null,
      txDataHash: BytesLike | null,
      l2DepositTxHash: BytesLike | null
    ): EventFilter;

    BridgehubDepositInitiatedSharedBridge(
      chainId: BigNumberish | null,
      txDataHash: BytesLike | null,
      from: string | null,
      to: null,
      l1Token: null,
      amount: null
    ): EventFilter;

    ClaimedFailedDepositSharedBridge(
      chainId: BigNumberish | null,
      to: string | null,
      l1Token: string | null,
      amount: null
    ): EventFilter;

    DepositInitiatedSharedBridge(
      chainId: BigNumberish | null,
      l2DepositTxHash: BytesLike | null,
      from: string | null,
      to: null,
      l1Token: null,
      amount: null
    ): EventFilter;

    WithdrawalFinalizedSharedBridge(
      chainId: BigNumberish | null,
      to: string | null,
      l1Token: string | null,
      amount: null
    ): EventFilter;
  };

  estimateGas: {
    bridgehub(overrides?: CallOverrides): Promise<BigNumber>;

    "bridgehub()"(overrides?: CallOverrides): Promise<BigNumber>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDeposit(uint256,address,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    deposit(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "deposit(uint256,address,address,uint256,uint256,uint256,uint256,address)"(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    isWithdrawalFinalizedShared(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isWithdrawalFinalizedShared(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bridgehub(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bridgehub()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDeposit(uint256,address,bytes)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _prevMsgSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    claimFailedDeposit(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimFailedDeposit(uint256,address,address,uint256,bytes32,uint256,uint256,uint16,bytes32[])"(
      _chainId: BigNumberish,
      _depositSender: string,
      _l1Token: string,
      _amount: BigNumberish,
      _l2TxHash: BytesLike,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    deposit(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "deposit(uint256,address,address,uint256,uint256,uint256,uint256,address)"(
      _chainId: BigNumberish,
      _l2Receiver: string,
      _l1Token: string,
      _mintValue: BigNumberish,
      _amount: BigNumberish,
      _l2TxGasLimit: BigNumberish,
      _l2TxGasPerPubdataByte: BigNumberish,
      _refundRecipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    depositHappened(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "depositHappened(uint256,bytes32)"(
      _chainId: BigNumberish,
      _l2TxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    finalizeWithdrawal(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "finalizeWithdrawal(uint256,uint256,uint256,uint16,bytes,bytes32[])"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      _l2TxNumberInBatch: BigNumberish,
      _message: BytesLike,
      _merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isWithdrawalFinalizedShared(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isWithdrawalFinalizedShared(uint256,uint256,uint256)"(
      _chainId: BigNumberish,
      _l2BatchNumber: BigNumberish,
      _l2MessageIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2BridgeAddress(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l2BridgeAddress(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
