/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetRouterBase,
  IAssetRouterBaseInterface,
} from "../IAssetRouterBase";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_assetAddress",
        type: "address",
      },
    ],
    name: "AssetHandlerRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "assetHandlerAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "additionalData",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "assetDeploymentTracker",
        type: "address",
      },
    ],
    name: "AssetHandlerRegisteredInitial",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BridgehubDepositBaseTokenInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "txDataHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "bridgeMintCalldata",
        type: "bytes",
      },
    ],
    name: "BridgehubDepositInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "assetDataHash",
        type: "bytes32",
      },
    ],
    name: "BridgehubWithdrawalInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "assetData",
        type: "bytes",
      },
    ],
    name: "DepositFinalizedAssetRouter",
    type: "event",
  },
  {
    inputs: [],
    name: "BRIDGE_HUB",
    outputs: [
      {
        internalType: "contract IBridgehub",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_assetId",
        type: "bytes32",
      },
    ],
    name: "assetHandlerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_chainId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_assetId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_transferData",
        type: "bytes",
      },
    ],
    name: "finalizeDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_assetRegistrationData",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_assetHandlerAddress",
        type: "address",
      },
    ],
    name: "setAssetHandlerAddressThisChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAssetRouterBase__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetRouterBaseInterface {
    return new Interface(_abi) as IAssetRouterBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetRouterBase {
    return new Contract(address, _abi, runner) as unknown as IAssetRouterBase;
  }
}
