/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IL2AssetRouter,
  IL2AssetRouterInterface,
} from "../IL2AssetRouter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_assetAddress",
        type: "address",
      },
    ],
    name: "AssetHandlerRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "assetHandlerAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "additionalData",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "assetDeploymentTracker",
        type: "address",
      },
    ],
    name: "AssetHandlerRegisteredInitial",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BridgehubDepositBaseTokenInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "txDataHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "bridgeMintCalldata",
        type: "bytes",
      },
    ],
    name: "BridgehubDepositInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "assetDataHash",
        type: "bytes32",
      },
    ],
    name: "BridgehubWithdrawalInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "assetData",
        type: "bytes",
      },
    ],
    name: "DepositFinalizedAssetRouter",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "l2Sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "assetData",
        type: "bytes",
      },
    ],
    name: "WithdrawalInitiatedAssetRouter",
    type: "event",
  },
  {
    inputs: [],
    name: "BRIDGE_HUB",
    outputs: [
      {
        internalType: "contract IBridgehub",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_assetId",
        type: "bytes32",
      },
    ],
    name: "assetHandlerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_chainId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_assetId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_transferData",
        type: "bytes",
      },
    ],
    name: "finalizeDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "l1AssetRouter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_originChainId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_assetId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_assetAddress",
        type: "address",
      },
    ],
    name: "setAssetHandlerAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_assetRegistrationData",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_assetHandlerAddress",
        type: "address",
      },
    ],
    name: "setAssetHandlerAddressThisChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_assetId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_transferData",
        type: "bytes",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_l1Receiver",
        type: "address",
      },
      {
        internalType: "address",
        name: "_l2Token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
    ],
    name: "withdrawLegacyBridge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IL2AssetRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IL2AssetRouterInterface {
    return new Interface(_abi) as IL2AssetRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IL2AssetRouter {
    return new Contract(address, _abi, runner) as unknown as IL2AssetRouter;
  }
}
