/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITestnetERC20Token,
  ITestnetERC20TokenInterface,
} from "../ITestnetERC20Token";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITestnetERC20Token__factory {
  static readonly abi = _abi;
  static createInterface(): ITestnetERC20TokenInterface {
    return new Interface(_abi) as ITestnetERC20TokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITestnetERC20Token {
    return new Contract(address, _abi, runner) as unknown as ITestnetERC20Token;
  }
}
