name: Publish NPM package
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "ref or tag to publish NPM package from"
        default: ""
        required: false
      tag:
        required: true
        type: choice
        description: package tag
        default: latest
        options:
          - latest
          - beta
          - ethers-v5-latest
          - ethers-v5-beta
          - zksyncos-alpha
jobs:
  zksync:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Build package and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run types
          npm run build
          node -p "require('./package.json').version"
          
      # Safety guard (optional but recommended)
      - name: Enforce safe dist-tag for zksyncos-alpha prereleases
        shell: bash
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          if [[ "$VERSION" == *"-zksyncos-alpha."* && "${{ inputs.tag }}" != "zksyncos-alpha" ]]; then
            echo "Refusing to publish $VERSION with dist-tag '${{ inputs.tag }}'. Use tag=zksyncos-alpha."
            exit 1
          fi
          if [[ "$VERSION" != *"-zksyncos-alpha."* && "${{ inputs.tag }}" == "zksyncos-alpha" ]]; then
            echo "Refusing to publish non-zksyncos version $VERSION under dist-tag zksyncos-alpha."
            exit 1
          fi
      
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag ${{ inputs.tag }}

  docs-build:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Build TypeDoc Documentation
    runs-on: ubuntu-latest
    needs: zksync
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Generate documentation
        run: yarn docs
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  docs-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
